# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created: Sun Jun 26 16:12:49 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_AddPostVK(object):
    def setupUi(self, AddPostVK):
        AddPostVK.setObjectName("AddPostVK")
        AddPostVK.resize(600, 600)
        AddPostVK.setMinimumSize(QtCore.QSize(600, 600))
        AddPostVK.setMaximumSize(QtCore.QSize(600, 600))
        self.layoutWidget = QtGui.QWidget(AddPostVK)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 581, 581))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtGui.QLabel(self.layoutWidget)
        self.label.setMaximumSize(QtCore.QSize(600, 16777215))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(False)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.label_2 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.login_le = QtGui.QLineEdit(self.layoutWidget)
        self.login_le.setObjectName("login_le")
        self.horizontalLayout_2.addWidget(self.login_le)
        self.password_le = QtGui.QLineEdit(self.layoutWidget)
        self.password_le.setObjectName("password_le")
        self.horizontalLayout_2.addWidget(self.password_le)
        self.autorization_b = QtGui.QPushButton(self.layoutWidget)
        self.autorization_b.setObjectName("autorization_b")
        self.horizontalLayout_2.addWidget(self.autorization_b)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.status_l = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(True)
        self.status_l.setFont(font)
        self.status_l.setObjectName("status_l")
        self.verticalLayout_2.addWidget(self.status_l)
        self.label_3 = QtGui.QLabel(self.layoutWidget)
        self.label_3.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.url_le = QtGui.QLineEdit(self.layoutWidget)
        self.url_le.setObjectName("url_le")
        self.horizontalLayout_6.addWidget(self.url_le)
        self.url_b = QtGui.QPushButton(self.layoutWidget)
        self.url_b.setObjectName("url_b")
        self.horizontalLayout_6.addWidget(self.url_b)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.label_4 = QtGui.QLabel(self.layoutWidget)
        self.label_4.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.id_group_l = QtGui.QLineEdit(self.layoutWidget)
        self.id_group_l.setObjectName("id_group_l")
        self.verticalLayout.addWidget(self.id_group_l)
        self.title_l = QtGui.QLineEdit(self.layoutWidget)
        self.title_l.setObjectName("title_l")
        self.verticalLayout.addWidget(self.title_l)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.tegs_l = QtGui.QLineEdit(self.layoutWidget)
        self.tegs_l.setObjectName("tegs_l")
        self.horizontalLayout_3.addWidget(self.tegs_l)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.text_t = QtGui.QTextEdit(self.layoutWidget)
        self.text_t.setObjectName("text_t")
        self.verticalLayout.addWidget(self.text_t)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.imgUrl_le = QtGui.QLineEdit(self.layoutWidget)
        self.imgUrl_le.setObjectName("imgUrl_le")
        self.horizontalLayout_5.addWidget(self.imgUrl_le)
        self.imgUrl_b = QtGui.QPushButton(self.layoutWidget)
        self.imgUrl_b.setObjectName("imgUrl_b")
        self.horizontalLayout_5.addWidget(self.imgUrl_b)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.label_5 = QtGui.QLabel(self.layoutWidget)
        self.label_5.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.send_status_l = QtGui.QLabel(self.layoutWidget)
        self.send_status_l.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(True)
        self.send_status_l.setFont(font)
        self.send_status_l.setText("")
        self.send_status_l.setObjectName("send_status_l")
        self.horizontalLayout_4.addWidget(self.send_status_l)
        self.year_le = QtGui.QLineEdit(self.layoutWidget)
        self.year_le.setObjectName("year_le")
        self.horizontalLayout_4.addWidget(self.year_le)
        self.month_le = QtGui.QLineEdit(self.layoutWidget)
        self.month_le.setObjectName("month_le")
        self.horizontalLayout_4.addWidget(self.month_le)
        self.day_le = QtGui.QLineEdit(self.layoutWidget)
        self.day_le.setObjectName("day_le")
        self.horizontalLayout_4.addWidget(self.day_le)
        self.hour_le = QtGui.QLineEdit(self.layoutWidget)
        self.hour_le.setObjectName("hour_le")
        self.horizontalLayout_4.addWidget(self.hour_le)
        self.minut_le = QtGui.QLineEdit(self.layoutWidget)
        self.minut_le.setObjectName("minut_le")
        self.horizontalLayout_4.addWidget(self.minut_le)
        self.send_b = QtGui.QPushButton(self.layoutWidget)
        self.send_b.setObjectName("send_b")
        self.horizontalLayout_4.addWidget(self.send_b)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)

        self.retranslateUi(AddPostVK)
        QtCore.QMetaObject.connectSlotsByName(AddPostVK)

    def retranslateUi(self, AddPostVK):
        AddPostVK.setWindowTitle(QtGui.QApplication.translate("AddPostVK", "Add post VK", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("AddPostVK", "Welcome to AddVkPost program! ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("AddPostVK", "Step 1:  Authorization", None, QtGui.QApplication.UnicodeUTF8))
        self.login_le.setText(QtGui.QApplication.translate("AddPostVK", "Login", None, QtGui.QApplication.UnicodeUTF8))
        self.password_le.setText(QtGui.QApplication.translate("AddPostVK", "Password", None, QtGui.QApplication.UnicodeUTF8))
        self.autorization_b.setText(QtGui.QApplication.translate("AddPostVK", "Аuthorization", None, QtGui.QApplication.UnicodeUTF8))
        self.status_l.setText(QtGui.QApplication.translate("AddPostVK", "You are not logged in!", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("AddPostVK", "Step 2:  Enter the link if the site is in the database or go to step 3", None, QtGui.QApplication.UnicodeUTF8))
        self.url_le.setText(QtGui.QApplication.translate("AddPostVK", "Url", None, QtGui.QApplication.UnicodeUTF8))
        self.url_b.setText(QtGui.QApplication.translate("AddPostVK", "Url", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("AddPostVK", "Step 3:  Enter the data for the post", None, QtGui.QApplication.UnicodeUTF8))
        self.id_group_l.setText(QtGui.QApplication.translate("AddPostVK", "Id group", None, QtGui.QApplication.UnicodeUTF8))
        self.title_l.setText(QtGui.QApplication.translate("AddPostVK", "Title", None, QtGui.QApplication.UnicodeUTF8))
        self.tegs_l.setText(QtGui.QApplication.translate("AddPostVK", "Tegs", None, QtGui.QApplication.UnicodeUTF8))
        self.text_t.setHtml(QtGui.QApplication.translate("AddPostVK", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Text post </p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.imgUrl_le.setText(QtGui.QApplication.translate("AddPostVK", "IMG url", None, QtGui.QApplication.UnicodeUTF8))
        self.imgUrl_b.setText(QtGui.QApplication.translate("AddPostVK", "Select a picture", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("AddPostVK", "Step 4:  Enter the time of publication and send", None, QtGui.QApplication.UnicodeUTF8))
        self.year_le.setText(QtGui.QApplication.translate("AddPostVK", "year", None, QtGui.QApplication.UnicodeUTF8))
        self.month_le.setText(QtGui.QApplication.translate("AddPostVK", "month", None, QtGui.QApplication.UnicodeUTF8))
        self.day_le.setText(QtGui.QApplication.translate("AddPostVK", "day", None, QtGui.QApplication.UnicodeUTF8))
        self.hour_le.setText(QtGui.QApplication.translate("AddPostVK", "hour", None, QtGui.QApplication.UnicodeUTF8))
        self.minut_le.setText(QtGui.QApplication.translate("AddPostVK", "minut", None, QtGui.QApplication.UnicodeUTF8))
        self.send_b.setText(QtGui.QApplication.translate("AddPostVK", "Send", None, QtGui.QApplication.UnicodeUTF8))

